name: track
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.3
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.2.2
  loading_overlay: ^0.3.0
  pin_code_fields: ^8.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/google.png

