// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOZBGpn4gH5CEznOD6oRYDzt_v2IOKv0E',
    appId: '1:29364402950:web:a1ee2fab60ef09272d7c87',
    messagingSenderId: '29364402950',
    projectId: 'track-8953d',
    authDomain: 'track-8953d.firebaseapp.com',
    storageBucket: 'track-8953d.firebasestorage.app',
    measurementId: 'G-CSN7KJPPW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWhVDaHeEpepwflESQore7kkD-wBL2_KY',
    appId: '1:29364402950:android:672d6aa524c06d4d2d7c87',
    messagingSenderId: '29364402950',
    projectId: 'track-8953d',
    storageBucket: 'track-8953d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj0gsxNlRpr-QwyiSPfI47AihpbkLIjYY',
    appId: '1:29364402950:ios:952fd1c1a715488c2d7c87',
    messagingSenderId: '29364402950',
    projectId: 'track-8953d',
    storageBucket: 'track-8953d.firebasestorage.app',
    iosBundleId: 'com.example.track',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj0gsxNlRpr-QwyiSPfI47AihpbkLIjYY',
    appId: '1:29364402950:ios:952fd1c1a715488c2d7c87',
    messagingSenderId: '29364402950',
    projectId: 'track-8953d',
    storageBucket: 'track-8953d.firebasestorage.app',
    iosBundleId: 'com.example.track',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOZBGpn4gH5CEznOD6oRYDzt_v2IOKv0E',
    appId: '1:29364402950:web:688e0901aa56dab32d7c87',
    messagingSenderId: '29364402950',
    projectId: 'track-8953d',
    authDomain: 'track-8953d.firebaseapp.com',
    storageBucket: 'track-8953d.firebasestorage.app',
    measurementId: 'G-K0JTVZ9M6K',
  );
}
